services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: node_object
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: wilson
      MYSQL_PASSWORD: 123456
    volumes:
      - ./deploy/sql_mount:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis
    volumes:
      - ./deploy/redis:/usr/local/etc/redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      timeout: 20s
      retries: 10

  node_object:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      db_host: mysql
      redis_host: redis
    ports:
      - "9330:9330"
#    volumes:
#      - ./deploy/api/dockerLog:/app/log
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy