services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: node_object
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: wilson
      MYSQL_PASSWORD: 123456
    volumes:
      - ./deploy/sql_mount:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis
    volumes:
      - ./deploy/redis_db:/usr/local/etc/redis_db
    healthcheck:
      test: [ "CMD", "redis_db-cli","ping" ]
      timeout: 20s
      retries: 10

  influxdb:
    image: influxdb
    volumes:
      - ./deploy/influxdb/data:/var/lib/influxdb2
      - ./deploy/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: wilson
      DOCKER_INFLUXDB_INIT_PASSWORD: 123456123456
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: node_object
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-influxdb-auth-token
    healthcheck:
      test: [ "CMD", "curl", "influxdb:8086/api/v2/ping" ]
      interval: 1m
      timeout: 10s
      retries: 5

  node_object:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      db_host: mysql
      redis_host: redis_db
      influx_host: influxdb
    ports:
      - "9330:9330"
#    volumes:
#      - ./deploy/api/dockerLog:/app/log
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy