redis:
  host: 127.0.0.1:6379
  user:
  password:
  db: 2
sql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: node_object
  pool_recycle: 3600
influxdb:
  host: 127.0.0.1
  port: 8086
  org: my-org
  token: my-super-influxdb-auth-token
  bucket: node_object
testSQL:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: node_object_test
  pool_recycle: 3600

server:
  port: 9330
  version: 2.7.11
  rear_timeout: 300  # s
  write_timeout: 300  # s

  account_using: True
  account_host: 192.168.1.10
  account_port: 9600

  redis_cb_db: 15
  redis_cb_bucket:  
